# Generate daily GARP scan report and optionally email
param([switch]$SendEmail)

$ErrorActionPreference = "Stop"
$Root = Split-Path (Split-Path $PSScriptRoot -Parent) -Parent
$ReportsDir = Join-Path $Root "research\reports"
$Watchlist = Join-Path $Root "portfolio\watchlist.yaml"
$Peak = Join-Path $Root "portfolio\peak-value.yaml"
New-Item -ItemType Directory -Force -Path $ReportsDir | Out-Null

$date = (Get-Date).ToUniversalTime().ToString("yyyy-MM-dd")
$reportFile = Join-Path $ReportsDir "$date-daily-garp-scan.md"

$body = @"
# Daily GARP Scan — $date

## Instructions for agent

1. Score all tickers in portfolio/watchlist.yaml via Rebalance-MCP (garp preset)
2. Flag score changes > 10 points since last_scored
3. Run compare_swaps for any swap candidates (delta >= 15)
4. Check drawdown status in portfolio/peak-value.yaml
5. Compare portfolio vs QQQ benchmark (FinanceKit)

## Output sections

- Top score changes
- Swap candidates
- Drawdown status
- Action items (dry-run only if paper trading active)

---
Generated by scripts/scoring/daily-garp-scan.ps1 — complete via Cursor agent + MCP.
"@

$body | Set-Content -Path $reportFile -Encoding UTF8
Write-Host "Scan template: $reportFile"

if ($SendEmail) {
    & (Join-Path (Split-Path $PSScriptRoot -Parent) "notify\send-email.ps1") `
        -Subject "1M Portfolio — Daily GARP Scan $date" `
        -Body "Daily scan ready. Open Cursor agent to complete MCP scoring. Report: $reportFile" `
        -Type "daily_scan"
}
